In [1]:
#question 1
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1], float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#question 2
import numpy

change_array = numpy.array(list(map(int,input().split())))
change_array.shape = (3, 3)
print (change_array)      



1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#question 3
import numpy
n , m = map(int,input().split())
my_array = numpy.array([input().split() for _ in range(n)], int)
print(numpy.transpose(my_array))
print(my_array.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [4]:
#question 4
import numpy

n , m  , p= map(int,input().split())
arr1 = numpy.array([input().split() for _ in range(n)], int)
arr2 = numpy.array([input().split() for _ in range(m)], int)
print(numpy.concatenate((arr1, arr2), axis = 0))


4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [1]:
#question 5
import numpy
n = list(map(int,input().split()))
print(numpy.zeros(n, dtype = int))
print(numpy.ones(n, dtype = int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [6]:
#question 6
import numpy
n , m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(a+b)
print(a-b)
print(a*b)
print(numpy.array(a/b,int))
print(a%b)
print(a**b)



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [7]:
#question 7
import numpy
numpy.set_printoptions(legacy = '1.13')
a = numpy.array(input().split(), float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [8]:
#question 8
import numpy
numpy.set_printoptions(legacy = '1.13')
n , m = map(int,input().split())
print(numpy.eye(n,m))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [9]:
#question 9
import numpy
n , m = map(int,input().split())
my_array = numpy.array([input().split() for _ in range(n)], int)
print (numpy.prod(numpy.sum(my_array, axis = 0)))


2 2 
1 2
3 4
24


In [10]:
#question 10
import numpy
n , m = map(int,input().split())
my_array = numpy.array([input().split() for _ in range(n)], int)
print (numpy.max(numpy.min(my_array, axis = 1)))


4 2
2 5
3 7
1 3
4 0
3


In [11]:
#question 11
import numpy
n , m = map(int,input().split())
my_array = numpy.array([input().split() for _ in range(n)], int)
print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
std = numpy.std(my_array)
rnd = numpy.around(std, 11)
print(rnd)



2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [12]:
#question 12
import numpy
n  = int(input())
a = numpy.array([list(map(int,input().split())) for _ in range(n)])
b = numpy.array([list(map(int,input().split())) for _ in range(n)])
print(numpy.dot(a, b))



2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [13]:
#question 13
import numpy

A = numpy.array(input().split(),int)
B = numpy.array(input().split(),int)
print(numpy.inner(A, B))
print(numpy.outer(A, B))



0 1
2 3
3
[[0 0]
 [2 3]]


In [14]:
#question 14
import numpy
a = list(map(float,input().split()))
n = input()
print(numpy.polyval(a,int(n)))


1.1 2 3
0
3.0


In [15]:
#question 15
import numpy
n = int(input())
a = numpy.array(numpy.array([input().split() for _ in range(n)],float))
print(numpy.linalg.det(a))



2
1.1 1.1
1.1 1.1
0.0
